*&---------------------------------------------------------------------*
*& Include          ZGY_P_TOP
*&---------------------------------------------------------------------*
TABLES:vbkd,vbak,vbap,kna1,vbep,veda,tvkot,tvtw,tvtwt,tspa,tspat,adrc,adcp,vbuk.

CLASS lcl_class DEFINITION DEFERRED.
DATA: go_local TYPE REF TO lcl_class.
DATA: go_alv_grid  TYPE REF TO cl_gui_alv_grid,
      go_container TYPE REF TO cl_gui_custom_container,
      gt_fcat      TYPE lvc_t_fcat,
      gs_fcat      TYPE lvc_s_fcat,
      gs_layout    TYPE lvc_s_layo.

TYPES:BEGIN OF gty_alv,
        vbeln    TYPE vbak-vbeln,
        bstkd    TYPE vbkd-bstkd,
        audat    TYPE vbak-audat,
        auart    TYPE vbak-auart,
        posnr    TYPE vbap-posnr,
        kunnr    TYPE vbak-kunnr,
        matnr    TYPE vbap-matnr,
        kwmeng   TYPE vbap-kwmeng,
        vrkme    TYPE vbap-vrkme,
        netwr_i  TYPE vbap-netwr,
        waerk    TYPE vbap-waerk,
        augru    TYPE vbak-augru,
        bstnk    TYPE vbak-bstnk,
        ernam    TYPE vbak-ernam,
        erdat    TYPE vbak-erdat,
        erzet    TYPE vbak-erzet,
        faksk    TYPE vbak-faksk,
        ktext    TYPE vbak-ktext,
        kurst    TYPE vbak-kurst,
        lifsk    TYPE vbak-lifsk,
        netwr_h  TYPE vbak-netwr,
        spart    TYPE vbak-spart,
        vbtyp    TYPE vbak-vbtyp,
        vkbur    TYPE vbak-vkbur,
        vkgrp    TYPE vbak-vkgrp,
        vkorg    TYPE vbak-vkorg,
        vtweg    TYPE vbak-vtweg,
        gbstk    TYPE vbak-gbstk,
        lfstk    TYPE vbak-lfstk,
        name1    TYPE kna1-name1,
        abgru    TYPE vbap-abgru,
        arktx    TYPE vbap-arktx,
        charg    TYPE vbap-charg,
        kbmeng   TYPE vbap-kbmeng,
        kmein    TYPE vbap-kmein,
        lgort    TYPE vbap-lgort,
        meins    TYPE vbap-meins,
        netpr    TYPE vbap-netpr,
        shkzg    TYPE vbap-shkzg,
        vstel    TYPE vbap-vstel,
        werks    TYPE vbap-werks,
        zmeng    TYPE vbap-zmeng,
        gbsta    TYPE vbap-gbsta,
        lfgsa    TYPE vbap-lfgsa,
        kursk    TYPE vbkd-kursk,
        prsdt    TYPE vbkd-prsdt,
        parvw    TYPE vbpa-parvw,
        pernr    TYPE vbpa-pernr,
        adrnr    TYPE kna1-adrnr,
        etenr    TYPE vbep-etenr,
        edatu    TYPE vbep-edatu,
        wmeng    TYPE vbep-wmeng,
        bmeng    TYPE vbep-bmeng,
        cmeng    TYPE vbep-cmeng,
        wadat    TYPE vbep-wadat,
        mbdat    TYPE vbep-mbdat,
        ettyp    TYPE vbep-ettyp,
        vlaufz   TYPE veda-vlaufz,
        vlauez   TYPE veda-vlauez,
        vlaufk   TYPE veda-vlaufk,
        vinsdat  TYPE veda-vinsdat,
        vabndat  TYPE veda-vabndat,
        vuntdat  TYPE veda-vuntdat,
        vbegdat  TYPE veda-vbegdat,
        venddat  TYPE veda-venddat,
        vkuesch  TYPE veda-vkuesch,
        vaktsch  TYPE veda-vaktsch,
        veindat  TYPE veda-veindat,
        vwundat  TYPE veda-vwundat,
        vkuepar  TYPE veda-vkuepar,
        vkuegru  TYPE veda-vkuegru,
        vbelkue  TYPE veda-vbelkue,
        vbedkue  TYPE veda-vbedkue,
        vdemdat  TYPE veda-vdemdat,
        vasda    TYPE veda-vasda,
        lifsk_d  TYPE val_text,"vbak-lifsk,
        faksk_d  TYPE val_text,"vbak-faksk,
        augru_d  TYPE val_text,"vbak-augru,
        abgru_d  TYPE val_text,"vbap-abgru,
        gbstk_d  TYPE val_text,"vbak-gbstk,
        lfstk_d  TYPE val_text,"vbak-lfstk,
        gbsta_d  TYPE val_text,"vbap-gbsta,
        lfsta_d  TYPE val_text,"vbap-lfsta,
        so_name  TYPE tvkot-vtext,
        dist_ch  TYPE tvtwt-vtext,
        div_name TYPE tspat-vtext,
        bezei    TYPE tvakt-bezei,
        sold_to  TYPE adrc-xpcpt,
        partner  TYPE adcp-xpcpt,
        actiond  TYPE veda-vaktsch,
      END OF gty_alv.

DATA:gt_alv TYPE TABLE OF gty_alv,
     gs_alv TYPE gty_alv.

FIELD-SYMBOLS:<lfd_statv>.

SELECTION-SCREEN BEGIN OF BLOCK a WITH FRAME TITLE TEXT-000.
SELECT-OPTIONS:so_vbeln FOR vbak-vbeln DEFAULT '4624',
               so_auart FOR vbak-auart,
               so_kunnr FOR vbak-kunnr,
               so_audat FOR vbak-audat,
               so_matnr FOR vbap-matnr,
               so_bstkd FOR vbkd-bstkd,
               so_erdat FOR vbak-erdat.
*NO INTERVALS.
SELECTION-SCREEN END OF BLOCK a.
